"""add_layer4_business_insights_schema

Revision ID: 94bc03e7215f
Revises: f614186293e5
Create Date: 2025-12-04 18:52:46.715180

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '94bc03e7215f'
down_revision: Union[str, None] = 'f614186293e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('business_scale', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_model', sa.String(length=100), nullable=True),
    sa.Column('annual_revenue', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('revenue_currency', sa.String(length=10), nullable=True),
    sa.Column('cash_reserves', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('debt_level', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('locations', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('primary_location', sa.String(length=100), nullable=True),
    sa.Column('supply_chain_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operational_dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_position', sa.String(length=50), nullable=True),
    sa.Column('market_share_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('key_competitors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('geographic_exposure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=True),
    sa.Column('vulnerability_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategic_priorities', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=100), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=100), nullable=True),
    sa.Column('ownership_type', sa.String(length=50), nullable=True),
    sa.Column('alert_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insight_customization', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_insight_generated', sa.TIMESTAMP(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_company_profiles_industry'), 'company_profiles', ['industry'], unique=False)
    op.create_index(op.f('ix_company_profiles_is_active'), 'company_profiles', ['is_active'], unique=False)
    op.create_table('competitive_intelligence',
    sa.Column('intel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('competitor_name', sa.String(length=200), nullable=True),
    sa.Column('competitor_industry', sa.String(length=100), nullable=True),
    sa.Column('intel_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('confidence_level', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('relevance_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('potential_opportunity', sa.Text(), nullable=True),
    sa.Column('suggested_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('intel_id')
    )
    op.create_index('idx_competitive_intel_company_time', 'competitive_intelligence', ['company_id', sa.text('detected_at DESC')], unique=False)
    op.create_index(op.f('ix_competitive_intelligence_company_id'), 'competitive_intelligence', ['company_id'], unique=False)
    op.create_index(op.f('ix_competitive_intelligence_status'), 'competitive_intelligence', ['status'], unique=False)
    op.create_table('insight_score_history',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('impact', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('final_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('triggering_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('time', 'insight_id')
    )
    op.create_index('idx_score_history_insight_time', 'insight_score_history', ['insight_id', sa.text('time DESC')], unique=False)
    op.create_index(op.f('ix_insight_score_history_insight_id'), 'insight_score_history', ['insight_id'], unique=False)
    op.create_table('insight_tracking',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('total_active_risks', sa.Integer(), nullable=True),
    sa.Column('total_active_opportunities', sa.Integer(), nullable=True),
    sa.Column('critical_risks', sa.Integer(), nullable=True),
    sa.Column('high_risks', sa.Integer(), nullable=True),
    sa.Column('medium_risks', sa.Integer(), nullable=True),
    sa.Column('low_risks', sa.Integer(), nullable=True),
    sa.Column('operational_risks', sa.Integer(), nullable=True),
    sa.Column('financial_risks', sa.Integer(), nullable=True),
    sa.Column('competitive_risks', sa.Integer(), nullable=True),
    sa.Column('reputational_risks', sa.Integer(), nullable=True),
    sa.Column('compliance_risks', sa.Integer(), nullable=True),
    sa.Column('strategic_risks', sa.Integer(), nullable=True),
    sa.Column('market_opportunities', sa.Integer(), nullable=True),
    sa.Column('cost_opportunities', sa.Integer(), nullable=True),
    sa.Column('strategic_opportunities', sa.Integer(), nullable=True),
    sa.Column('recommendations_generated', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.Integer(), nullable=True),
    sa.Column('actions_completed', sa.Integer(), nullable=True),
    sa.Column('risks_materialized', sa.Integer(), nullable=True),
    sa.Column('risks_avoided', sa.Integer(), nullable=True),
    sa.Column('opportunities_captured', sa.Integer(), nullable=True),
    sa.Column('opportunities_missed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'company_id')
    )
    op.create_index('idx_insight_tracking_company_time', 'insight_tracking', ['company_id', sa.text('time DESC')], unique=False)
    op.create_index(op.f('ix_insight_tracking_company_id'), 'insight_tracking', ['company_id'], unique=False)
    op.create_table('risk_opportunity_definitions',
    sa.Column('definition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('trigger_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_formula', sa.Text(), nullable=True),
    sa.Column('probability_formula', sa.Text(), nullable=True),
    sa.Column('urgency_formula', sa.Text(), nullable=True),
    sa.Column('default_impact', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('default_probability', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('default_urgency', sa.Integer(), nullable=True),
    sa.Column('applicable_industries', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('applicable_business_scales', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('explanation_template', sa.Text(), nullable=True),
    sa.Column('immediate_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('short_term_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medium_term_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('definition_id')
    )
    op.create_index(op.f('ix_risk_opportunity_definitions_category'), 'risk_opportunity_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_risk_opportunity_definitions_code'), 'risk_opportunity_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_risk_opportunity_definitions_is_active'), 'risk_opportunity_definitions', ['is_active'], unique=False)
    op.create_index(op.f('ix_risk_opportunity_definitions_type'), 'risk_opportunity_definitions', ['type'], unique=False)
    op.create_table('scenario_simulations',
    sa.Column('simulation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_name', sa.String(length=200), nullable=False),
    sa.Column('scenario_description', sa.Text(), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_contingencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preparation_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_index('idx_scenarios_company_time', 'scenario_simulations', ['company_id', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_scenario_simulations_company_id'), 'scenario_simulations', ['company_id'], unique=False)
    op.create_index(op.f('ix_scenario_simulations_status'), 'scenario_simulations', ['status'], unique=False)
    op.create_table('business_insights',
    sa.Column('insight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('insight_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('probability', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('impact', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('final_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_impact_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_duration_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('actual_impact', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('triggering_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_insights', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('affected_operations', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('requires_immediate_action', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['risk_opportunity_definitions.definition_id'], ),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_index('idx_insights_company_time', 'business_insights', ['company_id', sa.text('detected_at DESC')], unique=False)
    op.create_index('idx_insights_status_time', 'business_insights', ['status', sa.text('detected_at DESC')], unique=False)
    op.create_index('idx_insights_type_severity', 'business_insights', ['insight_type', 'severity_level'], unique=False)
    op.create_index(op.f('ix_business_insights_company_id'), 'business_insights', ['company_id'], unique=False)
    op.create_index(op.f('ix_business_insights_insight_type'), 'business_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_business_insights_is_urgent'), 'business_insights', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_business_insights_priority_rank'), 'business_insights', ['priority_rank'], unique=False)
    op.create_index(op.f('ix_business_insights_severity_level'), 'business_insights', ['severity_level'], unique=False)
    op.create_index(op.f('ix_business_insights_status'), 'business_insights', ['status'], unique=False)
    op.create_table('insight_feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('accuracy_rating', sa.Integer(), nullable=True),
    sa.Column('relevance_rating', sa.Integer(), nullable=True),
    sa.Column('usefulness_rating', sa.Integer(), nullable=True),
    sa.Column('timeliness_rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('did_risk_materialize', sa.Boolean(), nullable=True),
    sa.Column('did_opportunity_exist', sa.Boolean(), nullable=True),
    sa.Column('was_action_taken', sa.Boolean(), nullable=True),
    sa.Column('action_effectiveness', sa.String(length=50), nullable=True),
    sa.Column('actual_business_impact', sa.Text(), nullable=True),
    sa.Column('financial_impact_estimate', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('what_was_wrong', sa.Text(), nullable=True),
    sa.Column('what_was_missing', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('provided_by', sa.String(length=100), nullable=True),
    sa.Column('provided_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['business_insights.insight_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('idx_feedback_company_time', 'insight_feedback', ['company_id', sa.text('provided_at DESC')], unique=False)
    op.create_index(op.f('ix_insight_feedback_company_id'), 'insight_feedback', ['company_id'], unique=False)
    op.create_index(op.f('ix_insight_feedback_insight_id'), 'insight_feedback', ['insight_id'], unique=False)
    op.create_table('insight_recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('action_title', sa.String(length=200), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('responsible_role', sa.String(length=100), nullable=True),
    sa.Column('estimated_effort', sa.String(length=50), nullable=True),
    sa.Column('estimated_cost', sa.String(length=50), nullable=True),
    sa.Column('estimated_timeframe', sa.String(length=100), nullable=True),
    sa.Column('expected_benefit', sa.Text(), nullable=True),
    sa.Column('success_metrics', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('required_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('outcome_achieved', sa.Boolean(), nullable=True),
    sa.Column('actual_benefit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['business_insights.insight_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_insight_recommendations_insight_id'), 'insight_recommendations', ['insight_id'], unique=False)
    op.create_index(op.f('ix_insight_recommendations_priority'), 'insight_recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_insight_recommendations_status'), 'insight_recommendations', ['status'], unique=False)

    # Convert to TimescaleDB hypertables
    op.execute("SELECT create_hypertable('insight_tracking', 'time', if_not_exists => TRUE);")
    op.execute("SELECT create_hypertable('insight_score_history', 'time', if_not_exists => TRUE);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_recommendations_status'), table_name='insight_recommendations')
    op.drop_index(op.f('ix_insight_recommendations_priority'), table_name='insight_recommendations')
    op.drop_index(op.f('ix_insight_recommendations_insight_id'), table_name='insight_recommendations')
    op.drop_table('insight_recommendations')
    op.drop_index(op.f('ix_insight_feedback_insight_id'), table_name='insight_feedback')
    op.drop_index(op.f('ix_insight_feedback_company_id'), table_name='insight_feedback')
    op.drop_index('idx_feedback_company_time', table_name='insight_feedback')
    op.drop_table('insight_feedback')
    op.drop_index(op.f('ix_business_insights_status'), table_name='business_insights')
    op.drop_index(op.f('ix_business_insights_severity_level'), table_name='business_insights')
    op.drop_index(op.f('ix_business_insights_priority_rank'), table_name='business_insights')
    op.drop_index(op.f('ix_business_insights_is_urgent'), table_name='business_insights')
    op.drop_index(op.f('ix_business_insights_insight_type'), table_name='business_insights')
    op.drop_index(op.f('ix_business_insights_company_id'), table_name='business_insights')
    op.drop_index('idx_insights_type_severity', table_name='business_insights')
    op.drop_index('idx_insights_status_time', table_name='business_insights')
    op.drop_index('idx_insights_company_time', table_name='business_insights')
    op.drop_table('business_insights')
    op.drop_index(op.f('ix_scenario_simulations_status'), table_name='scenario_simulations')
    op.drop_index(op.f('ix_scenario_simulations_company_id'), table_name='scenario_simulations')
    op.drop_index('idx_scenarios_company_time', table_name='scenario_simulations')
    op.drop_table('scenario_simulations')
    op.drop_index(op.f('ix_risk_opportunity_definitions_type'), table_name='risk_opportunity_definitions')
    op.drop_index(op.f('ix_risk_opportunity_definitions_is_active'), table_name='risk_opportunity_definitions')
    op.drop_index(op.f('ix_risk_opportunity_definitions_code'), table_name='risk_opportunity_definitions')
    op.drop_index(op.f('ix_risk_opportunity_definitions_category'), table_name='risk_opportunity_definitions')
    op.drop_table('risk_opportunity_definitions')
    op.drop_index(op.f('ix_insight_tracking_company_id'), table_name='insight_tracking')
    op.drop_index('idx_insight_tracking_company_time', table_name='insight_tracking')
    op.drop_table('insight_tracking')
    op.drop_index(op.f('ix_insight_score_history_insight_id'), table_name='insight_score_history')
    op.drop_index('idx_score_history_insight_time', table_name='insight_score_history')
    op.drop_table('insight_score_history')
    op.drop_index(op.f('ix_competitive_intelligence_status'), table_name='competitive_intelligence')
    op.drop_index(op.f('ix_competitive_intelligence_company_id'), table_name='competitive_intelligence')
    op.drop_index('idx_competitive_intel_company_time', table_name='competitive_intelligence')
    op.drop_table('competitive_intelligence')
    op.drop_index(op.f('ix_company_profiles_is_active'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_industry'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
