"""add_extra_metadata_column

Revision ID: f614186293e5
Revises: aedc74724592
Create Date: 2025-12-04 15:21:07.544524

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f614186293e5'
down_revision: Union[str, None] = 'aedc74724592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_dependencies',
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('parent_indicator_id', sa.String(), nullable=True),
    sa.Column('child_indicator_id', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_indicator_id'], ['indicator_definitions.indicator_id'], ),
    sa.ForeignKeyConstraint(['parent_indicator_id'], ['indicator_definitions.indicator_id'], ),
    sa.PrimaryKeyConstraint('dependency_id')
    )
    op.create_index(op.f('ix_indicator_dependencies_dependency_id'), 'indicator_dependencies', ['dependency_id'], unique=False)
    op.create_table('indicator_thresholds',
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.String(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('color_code', sa.String(), nullable=True),
    sa.Column('severity_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator_definitions.indicator_id'], ),
    sa.PrimaryKeyConstraint('threshold_id')
    )
    op.create_index(op.f('ix_indicator_thresholds_threshold_id'), 'indicator_thresholds', ['threshold_id'], unique=False)
    op.add_column('article_indicator_mappings', sa.Column('match_type', sa.String(length=50), nullable=True))
    op.add_column('article_indicator_mappings', sa.Column('match_context', sa.Text(), nullable=True))
    op.drop_index('idx_article_mappings_article', table_name='article_indicator_mappings')
    op.drop_index('idx_article_mappings_confidence', table_name='article_indicator_mappings')
    op.drop_index('idx_article_mappings_indicator', table_name='article_indicator_mappings')
    op.drop_index('idx_article_mappings_method', table_name='article_indicator_mappings')
    op.create_index(op.f('ix_article_indicator_mappings_mapping_id'), 'article_indicator_mappings', ['mapping_id'], unique=False)
    op.drop_index('idx_correlation_date', table_name='indicator_correlations')
    op.drop_index('idx_correlation_indicators', table_name='indicator_correlations')
    op.drop_index('idx_correlation_significant', table_name='indicator_correlations')
    op.drop_constraint('indicator_correlations_indicator_id_1_indicator_id_2_calcul_key', 'indicator_correlations', type_='unique')
    op.add_column('indicator_definitions', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_indicator_active', table_name='indicator_definitions')
    op.drop_index('idx_indicator_pestel', table_name='indicator_definitions')
    op.drop_column('indicator_definitions', 'metadata')
    op.add_column('indicator_events', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_events_acknowledged', table_name='indicator_events')
    op.drop_index('idx_events_indicator_time', table_name='indicator_events')
    op.drop_index('idx_events_severity', table_name='indicator_events')
    op.drop_index('idx_events_type', table_name='indicator_events')
    op.drop_index('indicator_events_timestamp_idx', table_name='indicator_events')
    op.drop_column('indicator_events', 'metadata')
    op.drop_index('idx_keywords_active', table_name='indicator_keywords')
    op.drop_index('idx_keywords_indicator', table_name='indicator_keywords')
    op.drop_index('idx_keywords_text', table_name='indicator_keywords')
    op.drop_index('idx_keywords_text_gin', table_name='indicator_keywords', postgresql_using='gin')
    op.add_column('indicator_values', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_values_indicator_time', table_name='indicator_values')
    op.drop_index('idx_values_timestamp', table_name='indicator_values')
    op.drop_index('indicator_values_timestamp_idx', table_name='indicator_values')
    op.drop_column('indicator_values', 'metadata')
    op.add_column('ml_classification_results', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_ml_article', table_name='ml_classification_results')
    op.drop_index('idx_ml_created', table_name='ml_classification_results')
    op.drop_index('idx_ml_indicators_gin', table_name='ml_classification_results', postgresql_using='gin')
    op.drop_index('idx_ml_model', table_name='ml_classification_results')
    op.create_index(op.f('ix_ml_classification_results_article_id'), 'ml_classification_results', ['article_id'], unique=False)
    op.drop_column('ml_classification_results', 'metadata')
    op.add_column('trend_analysis', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_trend_direction', table_name='trend_analysis')
    op.drop_index('idx_trend_indicator_date', table_name='trend_analysis')
    op.drop_constraint('trend_analysis_indicator_id_analysis_date_window_days_key', 'trend_analysis', type_='unique')
    op.drop_column('trend_analysis', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_analysis', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint('trend_analysis_indicator_id_analysis_date_window_days_key', 'trend_analysis', ['indicator_id', 'analysis_date', 'window_days'])
    op.create_index('idx_trend_indicator_date', 'trend_analysis', ['indicator_id', 'analysis_date'], unique=False)
    op.create_index('idx_trend_direction', 'trend_analysis', ['trend_direction'], unique=False)
    op.drop_column('trend_analysis', 'extra_metadata')
    op.add_column('ml_classification_results', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ml_classification_results_article_id'), table_name='ml_classification_results')
    op.create_index('idx_ml_model', 'ml_classification_results', ['model_version'], unique=False)
    op.create_index('idx_ml_indicators_gin', 'ml_classification_results', ['predicted_indicators'], unique=False, postgresql_using='gin')
    op.create_index('idx_ml_created', 'ml_classification_results', ['created_at'], unique=False)
    op.create_index('idx_ml_article', 'ml_classification_results', ['article_id'], unique=False)
    op.drop_column('ml_classification_results', 'extra_metadata')
    op.add_column('indicator_values', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('indicator_values_timestamp_idx', 'indicator_values', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_values_timestamp', 'indicator_values', ['timestamp'], unique=False)
    op.create_index('idx_values_indicator_time', 'indicator_values', ['indicator_id', 'timestamp'], unique=False)
    op.drop_column('indicator_values', 'extra_metadata')
    op.create_index('idx_keywords_text_gin', 'indicator_keywords', ['keyword_text'], unique=False, postgresql_using='gin')
    op.create_index('idx_keywords_text', 'indicator_keywords', ['keyword_text'], unique=False)
    op.create_index('idx_keywords_indicator', 'indicator_keywords', ['indicator_id'], unique=False)
    op.create_index('idx_keywords_active', 'indicator_keywords', ['is_active'], unique=False)
    op.add_column('indicator_events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('indicator_events_timestamp_idx', 'indicator_events', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_events_type', 'indicator_events', ['event_type'], unique=False)
    op.create_index('idx_events_severity', 'indicator_events', ['severity'], unique=False)
    op.create_index('idx_events_indicator_time', 'indicator_events', ['indicator_id', 'timestamp'], unique=False)
    op.create_index('idx_events_acknowledged', 'indicator_events', ['acknowledged'], unique=False)
    op.drop_column('indicator_events', 'extra_metadata')
    op.add_column('indicator_definitions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('idx_indicator_pestel', 'indicator_definitions', ['pestel_category'], unique=False)
    op.create_index('idx_indicator_active', 'indicator_definitions', ['is_active'], unique=False)
    op.drop_column('indicator_definitions', 'extra_metadata')
    op.create_unique_constraint('indicator_correlations_indicator_id_1_indicator_id_2_calcul_key', 'indicator_correlations', ['indicator_id_1', 'indicator_id_2', 'calculation_date', 'lag_days'])
    op.create_index('idx_correlation_significant', 'indicator_correlations', ['is_significant'], unique=False)
    op.create_index('idx_correlation_indicators', 'indicator_correlations', ['indicator_id_1', 'indicator_id_2'], unique=False)
    op.create_index('idx_correlation_date', 'indicator_correlations', ['calculation_date'], unique=False)
    op.drop_index(op.f('ix_article_indicator_mappings_mapping_id'), table_name='article_indicator_mappings')
    op.create_index('idx_article_mappings_method', 'article_indicator_mappings', ['classification_method'], unique=False)
    op.create_index('idx_article_mappings_indicator', 'article_indicator_mappings', ['indicator_id'], unique=False)
    op.create_index('idx_article_mappings_confidence', 'article_indicator_mappings', ['match_confidence'], unique=False)
    op.create_index('idx_article_mappings_article', 'article_indicator_mappings', ['article_id'], unique=False)
    op.drop_column('article_indicator_mappings', 'match_context')
    op.drop_column('article_indicator_mappings', 'match_type')
    op.drop_index(op.f('ix_indicator_thresholds_threshold_id'), table_name='indicator_thresholds')
    op.drop_table('indicator_thresholds')
    op.drop_index(op.f('ix_indicator_dependencies_dependency_id'), table_name='indicator_dependencies')
    op.drop_table('indicator_dependencies')
    # ### end Alembic commands ###
